CREATE TABLE TAREFAS (
    ID INTEGER IDENTITY(1,1) NOT NULL,
    DATACRIACAO DATETIME NOT NULL,
    NOMETAREFA VARCHAR(100),
    RESPONSAVEL VARCHAR(30),
    STATUS CHAR(1),
	PRIORIDADE TINYINT,
    DATASTATUS DATE);
